### ISSUE TITLE
Filtro prodotti gratuiti

### ISSUE THREAD

**Issue by lbattt** [Neggia/SEM#48]
Aggiungere opzione per filtrare prodotti gratuiti.
Se un prodotto e' gratuito, va indicato

Indicare anche il mercato di provenienza

**Comment by Neggia** [comment]
Come fanno ad esserci prodotti gratuiti? Avevamo detto che andavano scartati per filtrare le offerte da coseinutili..

**Comment by lbattt** [comment]
> Come fanno ad esserci prodotti gratuiti? Avevamo detto che andavano scartati per filtrare le offerte da coseinutili..
@Neggia 
Ah non ricordavo , ma quindi scartiamo anche quelli come questo ?
![image](https://github.com/Neggia/SEM/assets/148484240/dffcbb0a-e8b8-4b05-81f4-244bf3a052f9)
 https://online.sinerville.com/mod/data/view.php?d=12&rid=307
Ce ne sono un po'

Io direi che scartarlo debba essere una flag a livello di sito , per ora solo su database

**Comment by Neggia** [comment]
Vedi tu, se riesci a trovare altro modo ben venga, era per evitare di inserire una miriade di casi speciali per ogni sito

**Comment by lbattt** [comment]
Per ora si , meglio scartarli se sono gratis. Fatto
