### ISSUE TITLE
Tema portale

### ISSUE THREAD

**Issue by lbattt** [Neggia/SEM#49]
Rifare il tema sfruttando la larghezza dello schermo su desktop , mostrando piu' prodotti per riga.
Assicurarsi che il layout sia a colonna su mobile.
Copiare stile e fonts da sito principale .

**Comment by lbattt** [comment]
@Neggia vedi se sembra carino

**Comment by Neggia** [comment]
Si molto carino, bravo, riporto ulteriori commenti dalla chat Telegram:
Che io ricordi per la sezione annunci si parlava di usare un plugin WordPress, quindi sarebbe un cosa separata dal motore di ricerca (eventualmente poi questo potrebbe recuperare i dati direttamente dal database e inserirli tra i risultati, visto che abbiamo il controllo di entrambe le interfacce?).
La sezione login per ora è necessaria solo agli Admin, riesci a farla scomparire in qualche modo per l'utente normale?
Aprendo il sito da cellulare per ora rimane in caricamento, è corretto che non si vedano prodotti? Ah no come non detto, ci ha messo una decina di secondi.. che opzioni abbiamo per velocizzare? Comunque dopo la prima volta, avendo scaricato le immagini, ci mette meno, magari si può vedere se la risoluzione di quelle è eccessiva.
Se abbiamo gli IP degli Admin potremmo fare un filtro in base a quello, incrementerebbe anche la sicurezza.
Altrimenti qualche cookie ma sarebbe più contorto.
Oppure sarebbe visibile solo collegandosi a un sottodominio speciale, forse la migliore soluzione tra le tre.

**Comment by lbattt** [comment]
Si anche secondo me  , un sottodominio speciale.
Chiedo su telegram.
Per il tempo di caricamento apro una issue  a parte.
Per le offerte aspettiamo cosa dicono
