### ISSUE TITLE
Leggere i log dei processi node.js in background

### ISSUE THREAD

**Issue by lbattt** [Neggia/SEM#57]
Se abbiamo schedulato processi node con `pm2` come spiegato in https://github.com/Neggia/SEM/issues/53:

leggere i log di ogni processo
`pm2 logs 0 --lines 1000`
dove 1000 e' il numero delle linee piu' recenti che si vogliono stampare , 0 e' l'id processo

**Comment by Neggia** [comment]
Ciao,
tutte queste cose di documentazione non è meglio inserirle nel ReadMe che poi esce nella home del progetto in GitHub? Altrimenti sono poi frammentate in tante issue che non vede nesuno, grazie

**Comment by lbattt** [comment]
fatto
